import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Header />
        <div className="w-full min-h-screen bg-slate-100 flex flex-col items-center justify-center space-y-8">
          {children}
        </div>
        <footer className="border-t border-slate-300 mt-auto py-8">
          <div className="max-w-7xl mx-auto px-6">
            <p className="text-xs text-black uppercase tracking-widest text-center">
              © 2026 LeadXP · All Rights Reserved
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}

